version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  microservice_a:
    restart: on-failure
    build:
      context: ./microservice_a/
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
  microservice_b:
    restart: on-failure
    build:
      context: ./microservice_b/
      dockerfile: ./Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
